---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "OctoPrint controls and monitor all aspects of your 3D printer and print jobs."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: octoprint
    gethomepage.dev/group: Apps
    gethomepage.dev/name: OctoPrint
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: self-hosted
          port: ${APP_PORT}
