---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./aeotec-zwave-device.yaml
  - ./amd-gpu.yaml
  - ./coral-device.yaml
  - ./intel-gpu.yaml
  - ./nabu-casa-zbt-2.yaml
  - ./nabu-casa-zwa-2.yaml
  - ./sonoff-zigbee-device.yaml
