---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nabu-casa-zbt-2-device
spec:
  rules:
    - labels:
        nabu-casa.feature.node.kubernetes.io/zbt-2: 'true'
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class:
              op: In
              value: ["ef"]
            device:
              op: In
              value: ["831a"]
            vendor:
              op: In
              value: ["303a"]
      name: nabu-casa.zbt-2
