---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    authentik.home.arpa/enabled: "true"
    gethomepage.dev/description: "Wordle Solver is a puzzle-solving assistant."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: mdi-puzzle
    gethomepage.dev/group: Apps
    gethomepage.dev/name: Wordle Solver
spec:
  hostnames:
    - "wordle.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: self-hosted
          port: ${APP_PORT}
