---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: drawio
  annotations:
    gethomepage.dev/description: "Draw.io is diagram software."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: draw-io.svg
    gethomepage.dev/group: Apps
    gethomepage.dev/name: Draw.io
spec:
  hostnames:
    - "drawio.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: drawio
          namespace: self-hosted
          port: ${APP_PORT}
