---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      data:
        # Authentik
        HOMEPAGE_VAR_AUTHENTIK_API_KEY: "{{ .AUTHENTIK_API_TOKEN }}"
        # Cloudflare
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_KEY: "{{ .CLOUDFLARE_API_TOKEN }}"
        # Grafana
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GF_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GF_ADMIN_PASSWORD }}"
        # Lidarr
        HOMEPAGE_VAR_LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
        # Miniflux
        HOMEPAGE_VAR_MINIFLUX_API_KEY: "{{ .MINIFLUX_API_KEY }}"
        # OpenWeatherMap
        HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY: "{{ .OPENWEATHERMAP_API_KEY }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .OPENWEATHERMAP_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .OPENWEATHERMAP_LONGITUDE }}"
        # Paperless
        HOMEPAGE_VAR_PAPERLESS_API_KEY: "{{ .PAPERLESS_API_KEY }}"
        # Plex
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_DEVICE_TOKEN }}"
        # qBittorrent
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        # ROMM
        HOMEPAGE_VAR_ROMM_USERNAME: "{{ .ROMM_USERNAME }}"
        HOMEPAGE_VAR_ROMM_PASSWORD: "{{ .ROMM_PASSWORD }}"
        # Radarr
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        # Sabnzbd
        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        # Sonarr
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        # Tandoor
        HOMEPAGE_VAR_TANDOOR_API_KEY: "{{ .TANDOOR_API_KEY }}"
        # Tautulli
        HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudflare
    - extract:
        key: grafana
    - extract:
        key: lidarr
    - extract:
        key: miniflux
    - extract:
        key: openweathermap
    - extract:
        key: paperless
    - extract:
        key: plex
    - extract:
        key: qbittorrent
    - extract:
        key: radarr
    - extract:
        key: romm
    - extract:
        key: sabnzbd
    - extract:
        key: sonarr
    - extract:
        key: tandoor
    - extract:
        key: tautulli
