---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Pinchflat manages media from online sources."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: pinchflat
    gethomepage.dev/group: Media
    gethomepage.dev/name: Pinchflat
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: media
          port: ${APP_PORT}
