---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - hostname: "${SECRET_DOMAIN_POC}"
    service: *svc
    originRequest:
      originServerName: "${SECRET_DOMAIN_POC}"
  - hostname: "*.${SECRET_DOMAIN_POC}"
    service: *svc
    originRequest:
      originServerName: "${SECRET_DOMAIN_POC}"
  - service: http_status:404
