# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloudflare-secret
stringData:
  api-token: ENC[AES256_GCM,data:KTgBsaSRe9tS3NbS+SJh0KoV7py2dDO0ZmBc3X7FY94kq39A3zU0lg==,iv:1WdKeN+omF7ekPxgbvzIng6idmVyeF5pIOwPMRNlFSQ=,tag:Bj4dPPff+q4MZo/qWiMqKQ==,type:str]
sops:
  age:
    - recipient: age19um8c7z6ckqsddthp6ecprlh69dg66kfwhfs9d6jvq7wze9pj5nqxy5dau
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZXJHVXdlNVRpSGtrTC9Z
        QnpzRjNjd2ROVXNqYUJCdnd1YTlaZTUxQ0NNCk5VU1hrdzk4dWgrZ3kyNTE1NlEx
        b2tnWno4NFU0amJjMVdLcHRFRjhPTzQKLS0tIDZ0M1hzaUVoRGluTERaR3VTWVl0
        Z3RBdm44VDhwUlRISGM4blRZN3Rsbm8Kc51N8C0GVruIKCZZY+qew+QMdTCEF+3F
        CjXemESTfdWlgS7fCQM2+ORW7jGZXp+p5KRJPogei/jvSjBGSjL+WQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T22:21:27Z"
  mac: ENC[AES256_GCM,data:MlHUiBefrSgkRRAUelJsQwDUyD8565HXDxa+AJTz6sUP5O1tP1tqglwHvjhK6ZqzZWIOr6oorjA1u8kV+nQ/SbQ0rTrmkb/TFK8dNwFeuwuwSxsiaqWHMFU0cqbJ4E2feEuxfiMJtYtVenPa+kASOfPt8VxxTxtav4DamArdhvY=,iv:mdazRj83u7+D8hNUtqgsVibbiqoZaGPpx+m3pl1D7mU=,tag:oC5dzyO0zDOtPMnA8F3kFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
