---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Sonarr is a TV manager."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: sonarr.svg
    gethomepage.dev/group: Media
    gethomepage.dev/name: Sonarr
    gethomepage.dev/widget.type: sonarr
    gethomepage.dev/widget.url: "http://sonarr.media.svc.cluster.local:${APP_PORT}"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: media
          port: ${APP_PORT}
