---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Open WebUI is a web interface for large language models."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: open-webui.svg
    gethomepage.dev/group: Apps
    gethomepage.dev/name: Open WebUI
spec:
  hostnames:
    - "chat.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: llm
          port: ${APP_PORT}
