# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-secret
    template:
      data:
        go2rtc.yaml: |
          log:
            streams: error
          api:
            listen: ":${APP_PORT}"
          rtsp:
            listen: ":554"
          webrtc:
            listen: ":8555"
          streams:
            3d-printer: ffmpeg:rtsp://192.168.4.4/live#video=h264#rotate=180
  dataFrom:
    - extract:
        key: go2rtc
