---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus
  annotations:
    gatus.home-operations.com/enabled: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: gatus.svg
    gethomepage.dev/group: Observability
    gethomepage.dev/name: Gatus
    gethomepage.dev/widget.type: gatus
    gethomepage.dev/widget.url: "http://gatus.observability.svc.cluster.local:${APP_PORT}"
spec:
  hostnames:
    - "status.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: gatus
          namespace: observability
          port: ${APP_PORT}
