---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wordpress-gds
  annotations:
    gethomepage.dev/description: WordPress
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: wordpress
    gethomepage.dev/name: WordPress GDS
spec:
  hostnames:
    - "wordpress-gds.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: wordpress-gds
          namespace: self-hosted
          port: ${APP_PORT}