---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Spoolman helps manage 3D printer filament spools and monitor their usage"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: spoolman
    gethomepage.dev/group: Apps
    gethomepage.dev/name: Spoolman
spec:
  hostnames:
    - "spoolman.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: self-hosted
          port: ${APP_PORT}
