---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
resources:
  - ./convertx/ks.yaml
  - ./drawio/ks.yaml
  - ./excalidraw/ks.yaml
  - ./filabridge/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./jrommanager/ks.yaml
  - ./miniflux/ks.yaml
  - ./octoprint/ks.yaml
  - ./spoolman/ks.yaml
