apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XoafdEbmc5OHnHaYaAT17Q==,iv:y7N04O6GnOysOa6A+kILHTr36EsY89nMb97cX9ND2yg=,tag:8cffAGG3LaBaBaU5f7OPVg==,type:str]
    SECRET_DOMAIN_POC: ENC[AES256_GCM,data:AjYhe/lqvoJDqcuCkNU=,iv:TVKV0NbJ6pzbBNtbJdmjoPRgV4TLM5uJtNSMtdi8eVk=,tag:g2TVIIcmWtD4DJiRhf9wHA==,type:str]
sops:
    age:
        - recipient: age19um8c7z6ckqsddthp6ecprlh69dg66kfwhfs9d6jvq7wze9pj5nqxy5dau
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWXVRNXF6ZFZqVTAvOEU3
            dlBNOVdmWlBlRnFYWnQxdUJTRGV0aHA2MkdBCkF1ZjdtbWF6NytuLzdZTDJDTGxS
            ZmI1clBRZHg3OEhjciszV24xVm1WS0UKLS0tIFVtUVNXNkM3OXZiMWdkdzB2aEJz
            M3A4T2c1SHErYkFVYUpGL3o4Tlg2M2sKGIIJCH4mr8RtcihUUfuksNp6MdcT8SnQ
            BVGrYZkuluOeNo/MNLKMfeS+9u/n7pq/d++J/69b1iRnDwWdOaROJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T19:44:43Z"
    mac: ENC[AES256_GCM,data:9AmvMaqg+h7hFHxZDX4sQxoIpBlaXs2vokrzGzYTMBNpSY0008YpMYAGPcQiQd6PKt3aWddHyJgUI9Yy/g3j8rvB+IEE+O0E8qximf4q3+kEmwmvLp1zT2tgwPQgQ3StsdjyBGGaEX2b69NmIq04Wg/xWAzmU5hFtsxBWfbPNp0=,iv:amsjVixw/vyGSHN1BT7vOIO06ge2SKciUI3RtSFac8o=,tag:58MEXAZUreeFISEcGU33oQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
