---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

# - search:
#   provider: duckduckgo
#   focus: true
#   target: _blank
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: cluster
    nodes:
      show: false
      cpu: false
      memory: false
      showLabel: false
- openweathermap:
  label: Bothell
  latitude: {{HOMEPAGE_VAR_LATITUDE}}
  longitude: {{HOMEPAGE_VAR_LONGITUDE}}
  units: imperial
  provider: openweathermap
  cache: 5
  format:
    maximumFractionDigits: 1
- datetime:
  text_size: m
  locale: en
  format:
    dateStyle: short
    timeStyle: short
    hour12: true
