---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: convertx
  annotations:
    gethomepage.dev/description: "ConvertX is file conversion service supporting a variety of formats."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: convertx
    gethomepage.dev/group: Apps
    gethomepage.dev/name: ConvertX
spec:
  hostnames:
    - "convertx.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: convertx
          namespace: self-hosted
          port: ${APP_PORT}
