---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "JRomManager is a ROM collections manager."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/optyfr/JRomManager@master/res-icons/src/main/java/jrm/resicons/rom.svg
    gethomepage.dev/group: Games
    gethomepage.dev/name: JRomManager
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: self-hosted
          port: ${APP_PORT}
