---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gatus.home-operations.com/endpoint: |-
      conditions: ["[STATUS] == 200"]
      path: /web/index.html
    gethomepage.dev/description: "Plex is a media server platform that organizes video, music, and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: plex.svg
    gethomepage.dev/group: Media
    gethomepage.dev/name: Plex
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: "http://plex.media.svc.cluster.local:${APP_PORT}"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: media
          port: ${APP_PORT}
