---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aqua.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./ingress-nginx.yaml
  - ./node-feature-discovery.yaml
