---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "FilaBridge is a service that bridges PrusaLink with Spoolman for inventory mangement."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: https://cdn.statically.io/gh/needo37/filabridge@main/static/images/3d-printer-icon.png
    gethomepage.dev/group: Apps
    gethomepage.dev/name: FilaBridge
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: self-hosted
          port: ${APP_PORT}
