---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: Zigbee Device Management
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home
    gethomepage.dev/icon: zigbee2mqtt
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=zigbee2mqtt"
spec:
  hostnames:
    - "zigbee2mqtt.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: home
          port: ${APP_PORT}
