---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Paperless is a document management system."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: paperless.svg
    gethomepage.dev/group: Apps
    gethomepage.dev/name: Paperless
    gethomepage.dev/widget.type: paperlessngx
    gethomepage.dev/widget.url: "http://paperless.default.svc.cluster.local:${APP_PORT}"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PAPERLESS_API_KEY}}"
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
    - "documents.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: default
          port: ${APP_PORT}
