---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: it-tools
  annotations:
    gethomepage.dev/description: "IT Tools is a collection of useful IT utilities."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: it-tools.svg
    gethomepage.dev/group: Apps
    gethomepage.dev/name: IT Tools
spec:
  hostnames:
    - "tools.${SECRET_DOMAIN}"
    - "it-tools.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: it-tools
          namespace: self-hosted
          port: ${APP_PORT}
