---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-poc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wordpress-poc-secret
    template:
      data:
        WORDPRESS_DB_USER: "{{ .WORDPRESS_DB_USER }}"
        WORDPRESS_DB_PASSWORD: "{{ .WORDPRESS_DB_PASSWORD }}"
        WORDPRESS_AUTH_KEY: "{{ .WORDPRESS_AUTH_KEY }}"
        WORDPRESS_SECURE_KEY: "{{ .WORDPRESS_SECURE_KEY }}"
        WORDPRESS_LOGGED_IN_KEY: "{{ .WORDPRESS_LOGGED_IN_KEY }}"
        WORDPRESS_NONCE_KEY: "{{ .WORDPRESS_NONCE_KEY }}"
        WORDPRESS_AUTH_SALT: "{{ .WORDPRESS_AUTH_SALT }}"
        WORDPRESS_SECURE_SALT: "{{ .WORDPRESS_SECURE_SALT }}"
        WORDPRESS_LOGGED_IN_SALT: "{{ .WORDPRESS_LOGGED_IN_SALT }}"
        WORDPRESS_NONCE_SALT: "{{ .WORDPRESS_NONCE_SALT }}"
  dataFrom:
    - extract:
        key: wordpress-poc
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-registry
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-registry
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .GHCR_USERNAME }}","password":"{{ .GHCR_TOKEN }}"}}}
  dataFrom:
    - extract:
        key: ghcr-registry
