---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wordpress-poc
  annotations:
    gethomepage.dev/description: WordPress POC
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Apps
    gethomepage.dev/icon: wordpress
    gethomepage.dev/name: WordPress POC
spec:
  hostnames:
    - "${SECRET_DOMAIN_POC}"
    - "www.${SECRET_DOMAIN_POC}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: wordpress-poc
          namespace: self-hosted
          port: ${APP_PORT}
