---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./externalsecret-wordpress-gds.yaml
  - ./externalsecret-wordpress-poc.yaml
  - ./mariadb-wordpress-gds.yaml
  - ./mariadb-wordpress-poc.yaml
  - ./backup-wordpress-gds.yaml
  - ./backup-wordpress-poc.yaml
