---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${APP}
  annotations:
    gethomepage.dev/description: "Lidarr is a music collection manager."
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: lidarr.svg
    gethomepage.dev/group: Media
    gethomepage.dev/name: Lidarr
    gethomepage.dev/widget.type: lidarr
    gethomepage.dev/widget.url: http://lidarr.media.svc.cluster.local:80
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_LIDARR_API_KEY}}"
spec:
  hostnames:
    - "${APP}.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: ${APP}
          namespace: media
          port: ${APP_PORT}
