---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: excalidraw
  annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: si-daigrams.net
          gethomepage.dev/name: excalidraw
          gethomepage.dev/group: Tools
          gethomepage.dev/description: Diagramming Tool
spec:
  hostnames:
    - "draw.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: excalidraw
          namespace: self-hosted
          port: ${APP_PORT}
